"""Central configuration defaults for the multiplayer server."""

from pathlib import Path


HOST = "127.0.0.1"
PORT = 8765
DATABASE_PATH = Path("data") / "kung_fu_chess.db"
TICK_INTERVAL_MS = 50
MAX_TICK_STEP_MS = 50
MATCHMAKING_RATING_RANGE = 100
MATCHMAKING_TIMEOUT_SECONDS = 60.0
RECONNECT_GRACE_PERIOD_SECONDS = 20.0
LOG_DIRECTORY = Path("logs")
SERVER_LOG_PATH = LOG_DIRECTORY / "server.log"
GAME_LOG_DIRECTORY = LOG_DIRECTORY / "games"
LOG_MAX_BYTES = 1_000_000
LOG_BACKUP_COUNT = 3
